apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-users-deployment
  labels:
    app: api-users
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-users
  template:
    metadata:
      labels:
        app: api-users
    spec:
      containers:
      - name: api-users
        image: mamanmeshak/api-users:v1
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef: 
              name: environment
          - secretRef:
              name: secret
