version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy
  api-users:
    build:
      context: ./api-user
    image: api-users:v1
  api-feed:
    build:
      context: ./api-feed
    image: api-feed:v1
  udagram-frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:local